### ISSUE TITLE
Generate Exif info fails on APK 5.1

### ISSUE THREAD

**Issue by Dirk--** [kartaview/upload-scripts#125]
trying _Generate Exif info from an KV metadata format file_ fails:

```
(upload-scripts) C:\Users\Dirk\upload-scripts>python osc_tools.py generate_exif --exif_source metadata -p C:\Users\Dirk\OSV\SEQ_d5271fb3-4032-4886-8dbf-02fa1d49801b

Trying to generating exif for images at path...

Creating exif from metadata file C:\Users\Dirk\OSV\SEQ_d5271fb3-4032-4886-8dbf-02fa1d49801b

Traceback (most recent call last):

  File "C:\Users\Dirk\kartaview-upload-scripts\osc_tools.py", line 243, in <module>
    main()

  File "C:\Users\Dirk\kartaview-upload-scripts\osc_tools.py", line 24, in main
    args.func(args)

  File "C:\Users\Dirk\kartaview-upload-scripts\osc_tools.py", line 128, in exif_generation_command
    create_exif(path, args.exif_source)

  File "C:\Users\Dirk\kartaview-upload-scripts\osc_utils.py", line 24, in create_exif
    exif_generators[exif_source].create_exif(path)

  File "C:\Users\Dirk\kartaview-upload-scripts\exif_data_generators\metadata_to_exif.py", line 62, in create_exif
    add_gps_tags(photo.path, tags)

  File "C:\Users\Dirk\kartaview-upload-scripts\parsers\exif.py", line 347, in add_gps_tags
    exif_bytes = piexif.dump(exif_dict)

  File "C:\Users\Dirk\kartaview-upload-scripts\lib\site-packages\piexif\_dump.py", line 74, in dump
    gps_set = _dict_to_bytes(gps_ifd, "GPS", zeroth_length + exif_length)

  File "C:\Users\Dirk\kartaview-upload-scripts\lib\site-packages\piexif\_dump.py", line 335, in _dict_to_bytes
    length_str, value_str, four_bytes_over = _value_to_bytes(raw_value,

  File "C:\Users\Dirk\kartaview-upload-scripts\lib\site-packages\piexif\_dump.py", line 247, in _value_to_bytes
    four_bytes_over = new_value

UnboundLocalError: local variable 'new_value' referenced before assignment
```

Source is  _Releases 16 5.1 - APK , METADATA:2.0 ..._

**Comment by Dirk--** [comment]
see also https://github.com/hMatoba/Piexif/issues/82

**Comment by salabogdan** [comment]
fixed by pull request: https://github.com/kartaview/upload-scripts/pull/130
