### ISSUE TITLE
Unable to download my images using osc_tools.py

### ISSUE THREAD

**Issue by chrisdebian** [kartaview/upload-scripts#141]
Hi, all.

I'd like to download some of the images that i've contributed. I've had a look at [how to do this](https://github.com/kartaview/upload-scripts), specifically the part entitled [3. Download Imagery based on user](https://github.com/kartaview/upload-scripts#3-download-imagery-based-on-user)

I've downloaded the osc_tools.py script, and have run it as per the instructions. I get an error message about the 'download' function, and have tried the destination location with and without quotes. 

![Screenshot from 2024-05-03 19-38-03](https://github.com/kartaview/upload-scripts/assets/17935223/aeac13f8-ec24-438d-ae80-497bfc737f3a)

Has anyone else had this problem? 

Thanks,

Chris.

**Comment by Zh9567** [comment]
I am also unable to download my images, but mine is showing a lot of errors. Here is the traceback (parts of the path to file omitted for privacy):

```
Traceback (most recent call last):
  File "...\upload-scripts-master\osc_tools.py", line 243, in <module>
    main()
    ~~~~^^
  File "...\upload-scripts-master\osc_tools.py", line 24, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "...\upload-scripts-master\osc_tools.py", line 136, in download_current_user_data
    download_user_images(path)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "...\upload-scripts-master\download.py", line 50, in download_user_images
    download_success, _ = _download_photo_sequence(osc_api,
                          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
                                                   sequence,
                                                   ^^^^^^^^^
                                                   sequence_path,
                                                   ^^^^^^^^^^^^^^
                                                   add_gps_to_exif=True)
                                                   ^^^^^^^^^^^^^^^^^^^^^
  File "...\upload-scripts-master\download.py", line 63, in _download_photo_sequence
    photos, error = osc_api.get_photos(sequence.online_id)
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "...\upload-scripts-master\osc_api_gateway.py", line 262, in get_photos
    photo = OSCPhoto.photo_from_json(photo_json)
  File "...\upload-scripts-master\osc_api_models.py", line 63, in photo_from_json
    photo.timestamp = datetime.datetime.strptime(shot_date, '%Y-%m-%d %H:%M:%S').timestamp()
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 676, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "...\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 458, in _strptime
    raise ValueError("unconverted data remains: %s" %
                      data_string[found.end():])
ValueError: unconverted data remains: .000
```
