### ISSUE TITLE
Rauth library error on Windows 10

### ISSUE THREAD

**Issue by sashabrava** [kartaview/upload-scripts#92]
Running upload scripts on Windows 10 version 1903 results with following error:

python osc_tools.py upload -p "(path_to_my_folder)"
Searching for sequences...
    Found sequence at path (path_to_my_folder). Sequence type Exif-Photo.
Search completed.

Starting to upload 1 sequences...
Traceback (most recent call last):
  File "osc_tools.py", line 212, in <module>
    main()
  File "osc_tools.py", line 22, in main
    args.func(args)
  File "osc_tools.py", line 119, in upload_command
    upload_manager.start_upload()
  File "C:\..\upload-scripts-master\osc_uploader.py", line 41, in start_upload
    user = self.login_controller.login()
  File "C:\..\upload-scripts-master\login_controller.py", line 59, in login
    osm_token, osm_secret = osm_auth(self.__prompt_user_for_login,
  File "C:\..\upload-scripts-master\osm_access.py", line 24, in osm_auth
    request_token, request_token_secret = auth_service.get_request_token()
  File "C:\..\upload-scripts-master\env\lib\site-packages\rauth\service.py", line 244, in get_request_token
    process_token_request(r, decoder, key_token, key_token_secret)
  File "C:\..\upload-scripts-master\env\lib\site-packages\rauth\service.py", line 20, in process_token_request
    data = decoder(r.content)
  File "C:\..\upload-scripts-master\env\lib\site-packages\rauth\utils.py", line 26, in parse_utf8_qsl
    for k, v in d.items():  # pragma: no cover
RuntimeError: dictionary keys changed during iteration

rauth version is 0.7.2
python version is 3.8.0.

**Comment by sashabrava** [comment]
The same error happened on Linux with Python 3.8, script was launched by switching to Python 3.7.0

**Comment by salabogdan** [comment]
@sashabrava please try using Python 3.6.

**Comment by salabogdan** [comment]
we changed the rauth library so this should no longer be an issue.
